---
title: Global Aid Match System
author: R package build
date: '2019-07-04'
slug: global-aid-match-system
categories: ["Blockchain", "Java", "GO"]
tags: ["software"]
subtitle: ''
summary: 'IBM Call for Code 2019 Global Challenge'
authors: []
#lastmod: '2022-04-04T18:15:12-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

In summer 2019, I participated in the IBM Call for Code competition as a member of the Bank of China team. The competition looked for innovative ideas on disaster relief issues. We were tackling the inefficient relief supply distribution, a problem caused by the lack of transparent information and trust. When a natural disaster happens, information acquisition between two parties that need and provide resources rely on traditional media. There are often information barriers between each other that lack a resource scheduling scheme. 

## Methods

To ensure mutual trust, blockchain was used in our solution as it has a transparent mechanism. Blockchain technology has the benefits of increased transparency in data shared on the network, contributing to enhanced trust among different organizations. During the development process, I used the Go language to implement chaincode, a “smart contract” that handled the demand and supply matching logic under the Hyperledger Fabric framework.

Based on blockchain, we built functions such as information release and evaluation systems. In addition, we formed the scheme of a matchmaking system to match the disaster-stricken party with the relief provider. The design also included a feedback mechanism for the participant organizations, and the results would affect the supply distribution priority of the next matchmaking. 

## Results

Through the development and research of the Global Aim Match System, the team formed a systematic disaster relief chain solution that would increase transparency and boost the efficiency of disaster assistance. Our project placed among the top five in the Greater China region.

*Check the GitHub repo [here](https://github.com/Avery7Li/GAS)*

*[Call for Code 2019 Global Challenge](https://developer.ibm.com/callforcode/solutions/2019-solutions/
)*